config/routes.rb
Rails.application.routes.draw do
  
  resources :seats
  resources :sears
  	root to: 'visitors#index'
     get "/change_locale" => "i18n#change_locale", :as => :change_locale
  locale_regex_string = HotDesk::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(HotDesk::REMOVED_LOCALES.to_a).join("|")
  locale_matcher = Regexp.new(locale_regex_string)
  scope "(/:locale)", :constraints => { :locale => locale_matcher } do
  	devise_for :users
  	resources :users
  	resources :seats
  	get '/book_seat' => "users#book_seat"
  	put '/assign_seat' => "users#assign_seat"
  end	 	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/seat.rb
class Seat < ApplicationRecord
	has_one :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  belongs_to :seat, optional: true

  validates_uniqueness_of :seat_id, if: :seat_id
  validate :date_range

  enum role: [:staff, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def seat_period
    if seat_from_date.present? && seat_end_date.present?
      "#{seat_from_date.strftime('%d-%m-%y')} to #{seat_end_date.strftime('%d-%m-%y')}"
    end
  end

  def self.send_seats_status

  end

  def set_default_role
    self.role ||= :staff
  end

  def date_range
    return unless self.seat_end_date
    return unless self.seat_from_date
    self.errors.add(:date_range, "end date should be greater than start date" ) unless self.seat_end_date >= self.seat_from_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  module DefaultURLOptions
	    # Adds locale to all links
	    def default_url_options
	      { :locale => I18n.locale }
	    end
  	end

  	include DefaultURLOptions

  	before_action :set_locale

  	def set_locale
  		I18n.locale = params[:locale] || 'en'
  	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/i18n_controller.rb
class I18nController < ApplicationController

  # Changes locale and returns to the previous view
  def change_locale
    redirect_to "/#{params[:locale]}/#{params[:redirect_uri]}"
  end

end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  # GET /seats
  # GET /seats.json
  def index
    @seats = Seat.all
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1
  # PATCH/PUT /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url, notice: 'Seat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_params
      params.require(:seat
        ).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def book_seat
    @user = current_user
    @seats = Seat.all
  end

  def assign_seat
    @seats = Seat.all
    @user = current_user
    respond_to do |format|
      if @user.update(seat_id: params[:seat_id], seat_from_date: params[:seat_from_date], seat_end_date: params[:seat_end_date] )
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :book_seat }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def user_params
      params.require(:user
        ).permit(:seat_id, :seat_from_date, :seat_end_date)
    end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def change_locale_path(is_logged_in:, locale:, redirect_uri:)
    if is_logged_in
      paths.change_locale_path(locale: locale, redirect_uri: redirect_uri)
    else
      path_after_locale_change(locale: locale, redirect_uri: redirect_uri)
    end
  end

  # Path after the current_user locale has been changed OR
  # the new locale path, if anonymous user.
  def path_after_locale_change(locale:, redirect_uri:)
    "/#{locale}/#{redirect_uri}"
  end

  def paths
    @_url_helpers ||= Rails.application.routes.url_helpers
  end

  def locale_change_links
  	new_path = request.fullpath.clone
    new_path.slice!("/#{params[:locale]}")
    new_path.slice!(0,1) if new_path =~ /^\//
    @return_to = new_path
    locales = HotDesk::AVAILABLE_LOCALES.map { |loc| [loc[:name], loc[:ident]] }
    locales.map { |(title, locale_code)|
      {
        url: change_locale_path(is_logged_in: current_user.present?,
                                            locale: locale_code,
                                            redirect_uri: @return_to),
        title: title
      }
    }
  end
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Staffs', users_path %></li>
  <% if current_user.admin? %>
  		<li><%= link_to 'Seats', seats_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Language
          </a>
          <ul class="dropdown-menu">
            <% locale_change_links.each do |locale_change_link| %>

              <li><a class="dropdown-item" href="<%= locale_change_link[:url]%>"><%= locale_change_link[:title]%></a></li>
            <% end %>  
          </ul>
        </li>
        
        <% if user_signed_in? %>
          <li>
            <%= link_to "Logged in, Hi #{current_user.name}" , "" %>
          </li>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Register', new_user_registration_path %></li>
        <% end %> 
      </ul>
    </div>
        
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hot Desk App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hot Desk App" %>">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <div class="container"> 
       <%= render 'layouts/messages' %>
       <%= yield %>
     </div>
    </main>
    <script type="text/javascript">
      $(document).ready(function(){
        $(".dropdown-toggle").dropdown();
      })
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/seats/_form.html.erb
  <%= form_with(model: seat, local: true) do |form| %>
    

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>

app/views/seats/edit.html.erb
<div class="authform">
	<h2>Editing Seat</h2>

	<%= render 'form', seat: @seat %>

	<%= link_to 'Show', @seat %> |
	<%= link_to 'Back', seats_path %>
</div>

app/views/seats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seats</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seats.each do |seat| %>
      <tr>
        <td><%= seat.name %></td>
        <td><%= link_to 'Show', seat %></td>
        <td><%= link_to 'Edit', edit_seat_path(seat) %></td>
        <td><%= link_to 'Destroy', seat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seat', new_seat_path %>

app/views/seats/new.html.erb
<div class="authform">
<h2>New Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Back', seats_path %>
</h2>

app/views/seats/show.html.erb
<div class="login-form">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @seat.name %>
	</p>

	<%= link_to 'Edit', edit_seat_path(@seat) %> |
	<%= link_to 'Back', seats_path %>
</div>

app/views/users/_user.html.erb
<td><%= user.name %></td>
<td><%= user.seat.try(:name) || ""%></td>
<td><%= user.try(:seat_period) %></td>
<td><%= link_to "Show", user %></td>

app/views/users/book_seat.html.erb
<div class="authform">
<h2>Book New Seat</h1>
	<% @user.errors.each do |attr, msg| %>
  <li style="color: red">
    <%= @user.errors.full_messages_for(attr).first if @user.errors[attr].first == msg %>
  </li>
<% end %>
 <%= form_for(current_user, :url => '/assign_seat', :html => { :method => :put, :role => 'form'}) do |form| %>
    

    <div class="form-group">
      <%= form.label :name %>
      <%= select_tag :seat_id, options_from_collection_for_select(@seats, "id", "name"), class: 'form-control' %>
    </div>
    <div class="form-group">
    	<%= form.label :from %>
    	<%= date_field_tag 'seat_from_date', params[:seat_from_date] || Date.today, class: 'form-control select_input'%>
	</div>
	<div class="form-group">
    	<%= form.label :to %>
    	<%= date_field_tag 'seat_end_date', params[:seat_end_date] || Date.today, class: 'form-control'%>
	</div>

    <div class="form-group">
      <%= form.submit "Submit", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>

<%= link_to 'Back', users_path %>
</h2>

<script type="text/javascript">
	
</script>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="column">
  <h2><%= link_to "Book New Seat", "/book_seat", class: 'button right', style: 'color: white'%></h2>
  </div>
  </div>
  <br>
  <div class="row">
    <div class="column">
      <table class="table table-striped">
        <thead  class="thead-dark">
          <tr>
            <th>Name</th>
            <th>Desk</th>
            <th>From/To</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="column">
		<h2>Staff Details</h2>
		<table>
			<tbody>
				<tr>
					<td>Name:</td>
					<td><%= @user.name if @user.name %></td>
				</tr>
				<tr>
					<td>Email:</td>
					<td><%= @user.email if @user.email %></td>
				</tr>
				<tr>
					<td>Desk:</td>
					<td><%= @user.seat.name if @user.seat %></td>
				</tr>
				<tr>
					<td>Date:</td>
					<td><%= @user.seat_period %></td>
				</tr>
			</tbody>
		</table>
	</div>
  </div>
</div>	
		

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p>Hot-desk app is an app to allow staff to book their desks and find
where their colleagues are sitting.</p>
<p><%= link_to 'Staffs:', users_path %> <%= User.count %>  booked seat(s)</p>